package pt.up.fe.labtablet.api;

import android.content.Context;
import android.os.AsyncTask;
import android.os.Environment;
import android.util.Log;

import com.itextpdf.text.Anchor;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chapter;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Section;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.Date;

import pt.up.fe.labtablet.R;
import pt.up.fe.labtablet.models.Form;
import pt.up.fe.labtablet.models.FormQuestion;

public class AsyncFormPDFGenerator extends AsyncTask<Object, Integer, String> {

    private AsyncTaskHandler<String> mHandler;
    private Exception error;
    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
            Font.BOLD);
    private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.NORMAL, BaseColor.RED);
    private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16,
            Font.BOLD);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);

    public AsyncFormPDFGenerator(AsyncTaskHandler<String> mHandler) {
        this.mHandler = mHandler;
    }

    @Override
    protected String doInBackground(Object... params) {

        //Form, Favorite Name, Context
        if (! (params[0] instanceof Form
                || params[1] instanceof String
                || params[2] instanceof Context)) {
            Log.e("PDF", "Wrong object types received!");
            return null;
        }

        Context mContext = (Context) params[2];
        String favoriteName = (String) params[1];
        Form form = (Form) params[0];

        String path = Environment.getExternalStorageDirectory()
                + "/" + mContext.getString(R.string.app_name)
                + "/" + favoriteName + "/"
                + form.getFormName() + "_" + new Date().getTime() + ".pdf";

        try {
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(path));
            document.open();

            addMetaData(document, form);
            addTitlePage(document, form);
            addContent(document, form);

            document.close();
        } catch (Exception e) {
            error = e;
        }
        return null;
    }

    @Override
    protected void onPostExecute(String result) {
        super.onPostExecute(result);
        if (error != null) {
            mHandler.onFailure(error);
        } else {
            mHandler.onSuccess(result);
        }
    }

    @Override
    protected void onProgressUpdate(Integer... values) {
        super.onProgressUpdate(values);
        mHandler.onProgressUpdate(values[0]);
    }

    private static void addMetaData(Document document, Form form) {
        document.addTitle(form.getFormName());
        document.addSubject(form.getFormDescription());
        //document.addKeywords("Java, PDF, iText");
        document.addAuthor("LabTablet");
        document.addCreator("LabTablet");
    }

    private static void addTitlePage(Document document, Form form)
            throws DocumentException {
        Paragraph preface = new Paragraph();
        preface.setAlignment(Element.ALIGN_CENTER);
        addEmptyLine(preface, 1);

        //PDF Header
        preface.add(new Paragraph(form.getFormName(), catFont));

        addEmptyLine(preface, 1);

        //Report generated by: name, date
        preface.add(new Paragraph("By: "
                + System.getProperty("user.name") + ", "
                + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
                smallBold));

        addEmptyLine(preface, 3);
        preface.add(new Paragraph(form.getFormDescription(),
                smallBold));

        addEmptyLine(preface, 8);

        Paragraph footer = new Paragraph(
                "Document generated with LabTablet application and the iTextPDF java library",
                redFont);

        footer.setAlignment(Element.ALIGN_BOTTOM);
        preface.add(footer);

        document.add(preface);
        document.newPage();
    }

    private static void addContent(Document document, Form form) throws DocumentException {
        Anchor anchor = new Anchor("Answers", catFont);
        anchor.setName("Answers");

        // Second parameter is the number of the chapter
        Chapter catPart = new Chapter(new Paragraph(anchor), 1);

        ArrayList<FormQuestion> fqs = form.getFormQuestions();
        for (FormQuestion fq : fqs) {
            Paragraph subPara = new Paragraph(fq.getQuestion(), subFont);
            Section subCatPart = catPart.addSection(subPara);
            subCatPart.add(new Paragraph("R: " + fq.getValue()));
            if(fq.isMandatory()) {
                subCatPart.add(new Paragraph("(required)"));
            }
        }

        // now add all this to the document
        document.add(catPart);

        // Build metrics section
        anchor = new Anchor("Gathered Metrics", catFont);
        anchor.setName("Gathered Metrics");
        catPart = new Chapter(new Paragraph(anchor), 2);

        createMetrics(catPart, form);
        // now add all this to the document
        document.add(catPart);
    }

    private static void createMetrics(Section subCatPart, Form form)
            throws BadElementException {

        PdfPTable table = new PdfPTable(3);
        PdfPCell c1 = new PdfPCell(new Phrase("Metric"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Value"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Unit"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        table.setHeaderRows(1);

        table.addCell("Date");
        table.addCell("" + new Date());
        table.addCell("N/A");

        table.addCell("Elapsed time");
        table.addCell(form.getElapsedTime());
        table.addCell("Seconds");

        table.addCell("Estimated time");
        table.addCell("" + form.getDuration());
        table.addCell("Seconds");

        table.addCell("# Questions");
        table.addCell("" + form.getFormQuestions().size());
        table.addCell("N/A");

        ArrayList<FormQuestion> formQuestions = form.getFormQuestions();
        int answeredCount = 0;
        for (FormQuestion fq : formQuestions) {
                if (fq.getValue() != null &&
                        !fq.getValue().equals("")) {

                    ++answeredCount;
                }
        }

        table.addCell("# Answered questions");
        table.addCell("" + answeredCount);
        table.addCell("N/A");

        subCatPart.add(table);
    }

    private static void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }
}